# 自动加载
autoload_for_url=yes
auto_load=yes

# 使用 uosc_danmaku 维护者提供的弹幕 API 代理
api_server=https://danmaku-api.152468.xyz

# 繁转简
chConvert=1

# 补帧弹幕平滑，费性能，不需要可以注释掉
vf_fps=yes
fps=60/1.001

# 弹幕字体大小
fontsize=25

# 弹幕透明度
opacity=0.25
